var country = [
    {
        "code": "AC",
        "unicode": "U+1F1E6 U+1F1E8",
        "name": "Ascension Island",
        "flag": "🇦🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AD",
        "unicode": "U+1F1E6 U+1F1E9",
        "name": "Andorra",
        "flag": "🇦🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AE",
        "unicode": "U+1F1E6 U+1F1EA",
        "name": "United Arab Emirates",
        "flag": "🇦🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AF",
        "unicode": "U+1F1E6 U+1F1EB",
        "name": "Afghanistan",
        "flag": "🇦🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AG",
        "unicode": "U+1F1E6 U+1F1EC",
        "name": "Antigua & Barbuda",
        "flag": "🇦🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AI",
        "unicode": "U+1F1E6 U+1F1EE",
        "name": "Anguilla",
        "flag": "🇦🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AL",
        "unicode": "U+1F1E6 U+1F1F1",
        "name": "Albania",
        "flag": "🇦🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AM",
        "unicode": "U+1F1E6 U+1F1F2",
        "name": "Armenia",
        "flag": "🇦🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AO",
        "unicode": "U+1F1E6 U+1F1F4",
        "name": "Angola",
        "flag": "🇦🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AQ",
        "unicode": "U+1F1E6 U+1F1F6",
        "name": "Antarctica",
        "flag": "🇦🇶",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AR",
        "unicode": "U+1F1E6 U+1F1F7",
        "name": "Argentina",
        "flag": "🇦🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AS",
        "unicode": "U+1F1E6 U+1F1F8",
        "name": "American Samoa",
        "flag": "🇦🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AT",
        "unicode": "U+1F1E6 U+1F1F9",
        "name": "Austria",
        "flag": "🇦🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AU",
        "unicode": "U+1F1E6 U+1F1FA",
        "name": "Australia",
        "flag": "🇦🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AW",
        "unicode": "U+1F1E6 U+1F1FC",
        "name": "Aruba",
        "flag": "🇦🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AX",
        "unicode": "U+1F1E6 U+1F1FD",
        "name": "Åland Islands",
        "flag": "🇦🇽",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "AZ",
        "unicode": "U+1F1E6 U+1F1FF",
        "name": "Azerbaijan",
        "flag": "🇦🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BA",
        "unicode": "U+1F1E7 U+1F1E6",
        "name": "Bosnia & Herzegovina",
        "flag": "🇧🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BB",
        "unicode": "U+1F1E7 U+1F1E7",
        "name": "Barbados",
        "flag": "🇧🇧",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BD",
        "unicode": "U+1F1E7 U+1F1E9",
        "name": "Bangladesh",
        "flag": "🇧🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BE",
        "unicode": "U+1F1E7 U+1F1EA",
        "name": "Belgium",
        "flag": "🇧🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BF",
        "unicode": "U+1F1E7 U+1F1EB",
        "name": "Burkina Faso",
        "flag": "🇧🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BG",
        "unicode": "U+1F1E7 U+1F1EC",
        "name": "Bulgaria",
        "flag": "🇧🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BH",
        "unicode": "U+1F1E7 U+1F1ED",
        "name": "Bahrain",
        "flag": "🇧🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BI",
        "unicode": "U+1F1E7 U+1F1EE",
        "name": "Burundi",
        "flag": "🇧🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BJ",
        "unicode": "U+1F1E7 U+1F1EF",
        "name": "Benin",
        "flag": "🇧🇯",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BL",
        "unicode": "U+1F1E7 U+1F1F1",
        "name": "St. Barthélemy",
        "flag": "🇧🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BM",
        "unicode": "U+1F1E7 U+1F1F2",
        "name": "Bermuda",
        "flag": "🇧🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BN",
        "unicode": "U+1F1E7 U+1F1F3",
        "name": "Brunei",
        "flag": "🇧🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BO",
        "unicode": "U+1F1E7 U+1F1F4",
        "name": "Bolivia",
        "flag": "🇧🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BQ",
        "unicode": "U+1F1E7 U+1F1F6",
        "name": "Caribbean Netherlands",
        "flag": "🇧🇶",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BR",
        "unicode": "U+1F1E7 U+1F1F7",
        "name": "Brazil",
        "flag": "🇧🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BS",
        "unicode": "U+1F1E7 U+1F1F8",
        "name": "Bahamas",
        "flag": "🇧🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BT",
        "unicode": "U+1F1E7 U+1F1F9",
        "name": "Bhutan",
        "flag": "🇧🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BV",
        "unicode": "U+1F1E7 U+1F1FB",
        "name": "Bouvet Island",
        "flag": "🇧🇻",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BW",
        "unicode": "U+1F1E7 U+1F1FC",
        "name": "Botswana",
        "flag": "🇧🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BY",
        "unicode": "U+1F1E7 U+1F1FE",
        "name": "Belarus",
        "flag": "🇧🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "BZ",
        "unicode": "U+1F1E7 U+1F1FF",
        "name": "Belize",
        "flag": "🇧🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CA",
        "unicode": "U+1F1E8 U+1F1E6",
        "name": "Canada",
        "flag": "🇨🇦",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "CC",
        "unicode": "U+1F1E8 U+1F1E8",
        "name": "Cocos (Keeling) Islands",
        "flag": "🇨🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CD",
        "unicode": "U+1F1E8 U+1F1E9",
        "name": "Congo - Kinshasa",
        "flag": "🇨🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CF",
        "unicode": "U+1F1E8 U+1F1EB",
        "name": "Central African Republic",
        "flag": "🇨🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CG",
        "unicode": "U+1F1E8 U+1F1EC",
        "name": "Congo - Brazzaville",
        "flag": "🇨🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CH",
        "unicode": "U+1F1E8 U+1F1ED",
        "name": "Switzerland",
        "flag": "🇨🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CI",
        "unicode": "U+1F1E8 U+1F1EE",
        "name": "Côte d’Ivoire",
        "flag": "🇨🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CK",
        "unicode": "U+1F1E8 U+1F1F0",
        "name": "Cook Islands",
        "flag": "🇨🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CL",
        "unicode": "U+1F1E8 U+1F1F1",
        "name": "Chile",
        "flag": "🇨🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CM",
        "unicode": "U+1F1E8 U+1F1F2",
        "name": "Cameroon",
        "flag": "🇨🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CN",
        "unicode": "U+1F1E8 U+1F1F3",
        "name": "China",
        "flag": "🇨🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CO",
        "unicode": "U+1F1E8 U+1F1F4",
        "name": "Colombia",
        "flag": "🇨🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CP",
        "unicode": "U+1F1E8 U+1F1F5",
        "name": "Clipperton Island",
        "flag": "🇨🇵",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CR",
        "unicode": "U+1F1E8 U+1F1F7",
        "name": "Costa Rica",
        "flag": "🇨🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CU",
        "unicode": "U+1F1E8 U+1F1FA",
        "name": "Cuba",
        "flag": "🇨🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CV",
        "unicode": "U+1F1E8 U+1F1FB",
        "name": "Cape Verde",
        "flag": "🇨🇻",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CW",
        "unicode": "U+1F1E8 U+1F1FC",
        "name": "Curaçao",
        "flag": "🇨🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CX",
        "unicode": "U+1F1E8 U+1F1FD",
        "name": "Christmas Island",
        "flag": "🇨🇽",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CY",
        "unicode": "U+1F1E8 U+1F1FE",
        "name": "Cyprus",
        "flag": "🇨🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "CZ",
        "unicode": "U+1F1E8 U+1F1FF",
        "name": "Czechia",
        "flag": "🇨🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "DE",
        "unicode": "U+1F1E9 U+1F1EA",
        "name": "Germany",
        "flag": "🇩🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "DG",
        "unicode": "U+1F1E9 U+1F1EC",
        "name": "Diego Garcia",
        "flag": "🇩🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "DJ",
        "unicode": "U+1F1E9 U+1F1EF",
        "name": "Djibouti",
        "flag": "🇩🇯",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "DK",
        "unicode": "U+1F1E9 U+1F1F0",
        "name": "Denmark",
        "flag": "🇩🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "DM",
        "unicode": "U+1F1E9 U+1F1F2",
        "name": "Dominica",
        "flag": "🇩🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "DO",
        "unicode": "U+1F1E9 U+1F1F4",
        "name": "Dominican Republic",
        "flag": "🇩🇴",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "DZ",
        "unicode": "U+1F1E9 U+1F1FF",
        "name": "Algeria",
        "flag": "🇩🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "EA",
        "unicode": "U+1F1EA U+1F1E6",
        "name": "Ceuta & Melilla",
        "flag": "🇪🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "EC",
        "unicode": "U+1F1EA U+1F1E8",
        "name": "Ecuador",
        "flag": "🇪🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "EE",
        "unicode": "U+1F1EA U+1F1EA",
        "name": "Estonia",
        "flag": "🇪🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "EG",
        "unicode": "U+1F1EA U+1F1EC",
        "name": "Egypt",
        "flag": "🇪🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "EH",
        "unicode": "U+1F1EA U+1F1ED",
        "name": "Western Sahara",
        "flag": "🇪🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ER",
        "unicode": "U+1F1EA U+1F1F7",
        "name": "Eritrea",
        "flag": "🇪🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ES",
        "unicode": "U+1F1EA U+1F1F8",
        "name": "Spain",
        "flag": "🇪🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ET",
        "unicode": "U+1F1EA U+1F1F9",
        "name": "Ethiopia",
        "flag": "🇪🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "EU",
        "unicode": "U+1F1EA U+1F1FA",
        "name": "European Union",
        "flag": "🇪🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "FI",
        "unicode": "U+1F1EB U+1F1EE",
        "name": "Finland",
        "flag": "🇫🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "FJ",
        "unicode": "U+1F1EB U+1F1EF",
        "name": "Fiji",
        "flag": "🇫🇯",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "FK",
        "unicode": "U+1F1EB U+1F1F0",
        "name": "Falkland Islands",
        "flag": "🇫🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "FM",
        "unicode": "U+1F1EB U+1F1F2",
        "name": "Micronesia",
        "flag": "🇫🇲",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "FO",
        "unicode": "U+1F1EB U+1F1F4",
        "name": "Faroe Islands",
        "flag": "🇫🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "FR",
        "unicode": "U+1F1EB U+1F1F7",
        "name": "France",
        "flag": "🇫🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GA",
        "unicode": "U+1F1EC U+1F1E6",
        "name": "Gabon",
        "flag": "🇬🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GB",
        "unicode": "U+1F1EC U+1F1E7",
        "name": "United Kingdom",
        "flag": "🇬🇧",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GD",
        "unicode": "U+1F1EC U+1F1E9",
        "name": "Grenada",
        "flag": "🇬🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GE",
        "unicode": "U+1F1EC U+1F1EA",
        "name": "Georgia",
        "flag": "🇬🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GF",
        "unicode": "U+1F1EC U+1F1EB",
        "name": "French Guiana",
        "flag": "🇬🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GG",
        "unicode": "U+1F1EC U+1F1EC",
        "name": "Guernsey",
        "flag": "🇬🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GH",
        "unicode": "U+1F1EC U+1F1ED",
        "name": "Ghana",
        "flag": "🇬🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GI",
        "unicode": "U+1F1EC U+1F1EE",
        "name": "Gibraltar",
        "flag": "🇬🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GL",
        "unicode": "U+1F1EC U+1F1F1",
        "name": "Greenland",
        "flag": "🇬🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GM",
        "unicode": "U+1F1EC U+1F1F2",
        "name": "Gambia",
        "flag": "🇬🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GN",
        "unicode": "U+1F1EC U+1F1F3",
        "name": "Guinea",
        "flag": "🇬🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GP",
        "unicode": "U+1F1EC U+1F1F5",
        "name": "Guadeloupe",
        "flag": "🇬🇵",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GQ",
        "unicode": "U+1F1EC U+1F1F6",
        "name": "Equatorial Guinea",
        "flag": "🇬🇶",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GR",
        "unicode": "U+1F1EC U+1F1F7",
        "name": "Greece",
        "flag": "🇬🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GS",
        "unicode": "U+1F1EC U+1F1F8",
        "name": "South Georgia & South Sandwich Islands",
        "flag": "🇬🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GT",
        "unicode": "U+1F1EC U+1F1F9",
        "name": "Guatemala",
        "flag": "🇬🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GU",
        "unicode": "U+1F1EC U+1F1FA",
        "name": "Guam",
        "flag": "🇬🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GW",
        "unicode": "U+1F1EC U+1F1FC",
        "name": "Guinea-Bissau",
        "flag": "🇬🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "GY",
        "unicode": "U+1F1EC U+1F1FE",
        "name": "Guyana",
        "flag": "🇬🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "HK",
        "unicode": "U+1F1ED U+1F1F0",
        "name": "Hong Kong SAR China",
        "flag": "🇭🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "HM",
        "unicode": "U+1F1ED U+1F1F2",
        "name": "Heard & McDonald Islands",
        "flag": "🇭🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "HN",
        "unicode": "U+1F1ED U+1F1F3",
        "name": "Honduras",
        "flag": "🇭🇳",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "HR",
        "unicode": "U+1F1ED U+1F1F7",
        "name": "Croatia",
        "flag": "🇭🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "HT",
        "unicode": "U+1F1ED U+1F1F9",
        "name": "Haiti",
        "flag": "🇭🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "HU",
        "unicode": "U+1F1ED U+1F1FA",
        "name": "Hungary",
        "flag": "🇭🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IC",
        "unicode": "U+1F1EE U+1F1E8",
        "name": "Canary Islands",
        "flag": "🇮🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ID",
        "unicode": "U+1F1EE U+1F1E9",
        "name": "Indonesia",
        "flag": "🇮🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IE",
        "unicode": "U+1F1EE U+1F1EA",
        "name": "Ireland",
        "flag": "🇮🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IL",
        "unicode": "U+1F1EE U+1F1F1",
        "name": "Israel",
        "flag": "🇮🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IM",
        "unicode": "U+1F1EE U+1F1F2",
        "name": "Isle of Man",
        "flag": "🇮🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IN",
        "unicode": "U+1F1EE U+1F1F3",
        "name": "India",
        "flag": "🇮🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IO",
        "unicode": "U+1F1EE U+1F1F4",
        "name": "British Indian Ocean Territory",
        "flag": "🇮🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IQ",
        "unicode": "U+1F1EE U+1F1F6",
        "name": "Iraq",
        "flag": "🇮🇶",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IR",
        "unicode": "U+1F1EE U+1F1F7",
        "name": "Iran",
        "flag": "🇮🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IS",
        "unicode": "U+1F1EE U+1F1F8",
        "name": "Iceland",
        "flag": "🇮🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "IT",
        "unicode": "U+1F1EE U+1F1F9",
        "name": "Italy",
        "flag": "🇮🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "JE",
        "unicode": "U+1F1EF U+1F1EA",
        "name": "Jersey",
        "flag": "🇯🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "JM",
        "unicode": "U+1F1EF U+1F1F2",
        "name": "Jamaica",
        "flag": "🇯🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "JO",
        "unicode": "U+1F1EF U+1F1F4",
        "name": "Jordan",
        "flag": "🇯🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "JP",
        "unicode": "U+1F1EF U+1F1F5",
        "name": "Japan",
        "flag": "🇯🇵",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KE",
        "unicode": "U+1F1F0 U+1F1EA",
        "name": "Kenya",
        "flag": "🇰🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KG",
        "unicode": "U+1F1F0 U+1F1EC",
        "name": "Kyrgyzstan",
        "flag": "🇰🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KH",
        "unicode": "U+1F1F0 U+1F1ED",
        "name": "Cambodia",
        "flag": "🇰🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KI",
        "unicode": "U+1F1F0 U+1F1EE",
        "name": "Kiribati",
        "flag": "🇰🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KM",
        "unicode": "U+1F1F0 U+1F1F2",
        "name": "Comoros",
        "flag": "🇰🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KN",
        "unicode": "U+1F1F0 U+1F1F3",
        "name": "St. Kitts & Nevis",
        "flag": "🇰🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KP",
        "unicode": "U+1F1F0 U+1F1F5",
        "name": "North Korea",
        "flag": "🇰🇵",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KR",
        "unicode": "U+1F1F0 U+1F1F7",
        "name": "South Korea",
        "flag": "🇰🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KW",
        "unicode": "U+1F1F0 U+1F1FC",
        "name": "Kuwait",
        "flag": "🇰🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KY",
        "unicode": "U+1F1F0 U+1F1FE",
        "name": "Cayman Islands",
        "flag": "🇰🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "KZ",
        "unicode": "U+1F1F0 U+1F1FF",
        "name": "Kazakhstan",
        "flag": "🇰🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LA",
        "unicode": "U+1F1F1 U+1F1E6",
        "name": "Laos",
        "flag": "🇱🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LB",
        "unicode": "U+1F1F1 U+1F1E7",
        "name": "Lebanon",
        "flag": "🇱🇧",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LC",
        "unicode": "U+1F1F1 U+1F1E8",
        "name": "St. Lucia",
        "flag": "🇱🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LI",
        "unicode": "U+1F1F1 U+1F1EE",
        "name": "Liechtenstein",
        "flag": "🇱🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LK",
        "unicode": "U+1F1F1 U+1F1F0",
        "name": "Sri Lanka",
        "flag": "🇱🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LR",
        "unicode": "U+1F1F1 U+1F1F7",
        "name": "Liberia",
        "flag": "🇱🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LS",
        "unicode": "U+1F1F1 U+1F1F8",
        "name": "Lesotho",
        "flag": "🇱🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LT",
        "unicode": "U+1F1F1 U+1F1F9",
        "name": "Lithuania",
        "flag": "🇱🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LU",
        "unicode": "U+1F1F1 U+1F1FA",
        "name": "Luxembourg",
        "flag": "🇱🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LV",
        "unicode": "U+1F1F1 U+1F1FB",
        "name": "Latvia",
        "flag": "🇱🇻",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "LY",
        "unicode": "U+1F1F1 U+1F1FE",
        "name": "Libya",
        "flag": "🇱🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MA",
        "unicode": "U+1F1F2 U+1F1E6",
        "name": "Morocco",
        "flag": "🇲🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MC",
        "unicode": "U+1F1F2 U+1F1E8",
        "name": "Monaco",
        "flag": "🇲🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MD",
        "unicode": "U+1F1F2 U+1F1E9",
        "name": "Moldova",
        "flag": "🇲🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ME",
        "unicode": "U+1F1F2 U+1F1EA",
        "name": "Montenegro",
        "flag": "🇲🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MF",
        "unicode": "U+1F1F2 U+1F1EB",
        "name": "St. Martin",
        "flag": "🇲🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MG",
        "unicode": "U+1F1F2 U+1F1EC",
        "name": "Madagascar",
        "flag": "🇲🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MH",
        "unicode": "U+1F1F2 U+1F1ED",
        "name": "Marshall Islands",
        "flag": "🇲🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MK",
        "unicode": "U+1F1F2 U+1F1F0",
        "name": "Macedonia",
        "flag": "🇲🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ML",
        "unicode": "U+1F1F2 U+1F1F1",
        "name": "Mali",
        "flag": "🇲🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MM",
        "unicode": "U+1F1F2 U+1F1F2",
        "name": "Myanmar (Burma)",
        "flag": "🇲🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MN",
        "unicode": "U+1F1F2 U+1F1F3",
        "name": "Mongolia",
        "flag": "🇲🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MO",
        "unicode": "U+1F1F2 U+1F1F4",
        "name": "Macau SAR China",
        "flag": "🇲🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MP",
        "unicode": "U+1F1F2 U+1F1F5",
        "name": "Northern Mariana Islands",
        "flag": "🇲🇵",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MQ",
        "unicode": "U+1F1F2 U+1F1F6",
        "name": "Martinique",
        "flag": "🇲🇶",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MR",
        "unicode": "U+1F1F2 U+1F1F7",
        "name": "Mauritania",
        "flag": "🇲🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MS",
        "unicode": "U+1F1F2 U+1F1F8",
        "name": "Montserrat",
        "flag": "🇲🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MT",
        "unicode": "U+1F1F2 U+1F1F9",
        "name": "Malta",
        "flag": "🇲🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MU",
        "unicode": "U+1F1F2 U+1F1FA",
        "name": "Mauritius",
        "flag": "🇲🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MV",
        "unicode": "U+1F1F2 U+1F1FB",
        "name": "Maldives",
        "flag": "🇲🇻",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MW",
        "unicode": "U+1F1F2 U+1F1FC",
        "name": "Malawi",
        "flag": "🇲🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MX",
        "unicode": "U+1F1F2 U+1F1FD",
        "name": "Mexico",
        "flag": "🇲🇽",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MY",
        "unicode": "U+1F1F2 U+1F1FE",
        "name": "Malaysia",
        "flag": "🇲🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "MZ",
        "unicode": "U+1F1F2 U+1F1FF",
        "name": "Mozambique",
        "flag": "🇲🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NA",
        "unicode": "U+1F1F3 U+1F1E6",
        "name": "Namibia",
        "flag": "🇳🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NC",
        "unicode": "U+1F1F3 U+1F1E8",
        "name": "New Caledonia",
        "flag": "🇳🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NE",
        "unicode": "U+1F1F3 U+1F1EA",
        "name": "Niger",
        "flag": "🇳🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NF",
        "unicode": "U+1F1F3 U+1F1EB",
        "name": "Norfolk Island",
        "flag": "🇳🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NG",
        "unicode": "U+1F1F3 U+1F1EC",
        "name": "Nigeria",
        "flag": "🇳🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NI",
        "unicode": "U+1F1F3 U+1F1EE",
        "name": "Nicaragua",
        "flag": "🇳🇮",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "NL",
        "unicode": "U+1F1F3 U+1F1F1",
        "name": "Netherlands",
        "flag": "🇳🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NO",
        "unicode": "U+1F1F3 U+1F1F4",
        "name": "Norway",
        "flag": "🇳🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NP",
        "unicode": "U+1F1F3 U+1F1F5",
        "name": "Nepal",
        "flag": "🇳🇵",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NR",
        "unicode": "U+1F1F3 U+1F1F7",
        "name": "Nauru",
        "flag": "🇳🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NU",
        "unicode": "U+1F1F3 U+1F1FA",
        "name": "Niue",
        "flag": "🇳🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "NZ",
        "unicode": "U+1F1F3 U+1F1FF",
        "name": "New Zealand",
        "flag": "🇳🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "OM",
        "unicode": "U+1F1F4 U+1F1F2",
        "name": "Oman",
        "flag": "🇴🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PA",
        "unicode": "U+1F1F5 U+1F1E6",
        "name": "Panama",
        "flag": "🇵🇦",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "PE",
        "unicode": "U+1F1F5 U+1F1EA",
        "name": "Peru",
        "flag": "🇵🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PF",
        "unicode": "U+1F1F5 U+1F1EB",
        "name": "French Polynesia",
        "flag": "🇵🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PG",
        "unicode": "U+1F1F5 U+1F1EC",
        "name": "Papua New Guinea",
        "flag": "🇵🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PH",
        "unicode": "U+1F1F5 U+1F1ED",
        "name": "Philippines",
        "flag": "🇵🇭",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "PK",
        "unicode": "U+1F1F5 U+1F1F0",
        "name": "Pakistan",
        "flag": "🇵🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PL",
        "unicode": "U+1F1F5 U+1F1F1",
        "name": "Poland",
        "flag": "🇵🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PM",
        "unicode": "U+1F1F5 U+1F1F2",
        "name": "St. Pierre & Miquelon",
        "flag": "🇵🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PN",
        "unicode": "U+1F1F5 U+1F1F3",
        "name": "Pitcairn Islands",
        "flag": "🇵🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PR",
        "unicode": "U+1F1F5 U+1F1F7",
        "name": "Puerto Rico",
        "flag": "🇵🇷",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "PS",
        "unicode": "U+1F1F5 U+1F1F8",
        "name": "Palestinian Territories",
        "flag": "🇵🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PT",
        "unicode": "U+1F1F5 U+1F1F9",
        "name": "Portugal",
        "flag": "🇵🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "PW",
        "unicode": "U+1F1F5 U+1F1FC",
        "name": "Palau",
        "flag": "🇵🇼",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "PY",
        "unicode": "U+1F1F5 U+1F1FE",
        "name": "Paraguay",
        "flag": "🇵🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "QA",
        "unicode": "U+1F1F6 U+1F1E6",
        "name": "Qatar",
        "flag": "🇶🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "RE",
        "unicode": "U+1F1F7 U+1F1EA",
        "name": "Réunion",
        "flag": "🇷🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "RO",
        "unicode": "U+1F1F7 U+1F1F4",
        "name": "Romania",
        "flag": "🇷🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "RS",
        "unicode": "U+1F1F7 U+1F1F8",
        "name": "Serbia",
        "flag": "🇷🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "RU",
        "unicode": "U+1F1F7 U+1F1FA",
        "name": "Russia",
        "flag": "🇷🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "RW",
        "unicode": "U+1F1F7 U+1F1FC",
        "name": "Rwanda",
        "flag": "🇷🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SA",
        "unicode": "U+1F1F8 U+1F1E6",
        "name": "Saudi Arabia",
        "flag": "🇸🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SB",
        "unicode": "U+1F1F8 U+1F1E7",
        "name": "Solomon Islands",
        "flag": "🇸🇧",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SC",
        "unicode": "U+1F1F8 U+1F1E8",
        "name": "Seychelles",
        "flag": "🇸🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SD",
        "unicode": "U+1F1F8 U+1F1E9",
        "name": "Sudan",
        "flag": "🇸🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SE",
        "unicode": "U+1F1F8 U+1F1EA",
        "name": "Sweden",
        "flag": "🇸🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SG",
        "unicode": "U+1F1F8 U+1F1EC",
        "name": "Singapore",
        "flag": "🇸🇬",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "SH",
        "unicode": "U+1F1F8 U+1F1ED",
        "name": "St. Helena",
        "flag": "🇸🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SI",
        "unicode": "U+1F1F8 U+1F1EE",
        "name": "Slovenia",
        "flag": "🇸🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SJ",
        "unicode": "U+1F1F8 U+1F1EF",
        "name": "Svalbard & Jan Mayen",
        "flag": "🇸🇯",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SK",
        "unicode": "U+1F1F8 U+1F1F0",
        "name": "Slovakia",
        "flag": "🇸🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SL",
        "unicode": "U+1F1F8 U+1F1F1",
        "name": "Sierra Leone",
        "flag": "🇸🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SM",
        "unicode": "U+1F1F8 U+1F1F2",
        "name": "San Marino",
        "flag": "🇸🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SN",
        "unicode": "U+1F1F8 U+1F1F3",
        "name": "Senegal",
        "flag": "🇸🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SO",
        "unicode": "U+1F1F8 U+1F1F4",
        "name": "Somalia",
        "flag": "🇸🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SR",
        "unicode": "U+1F1F8 U+1F1F7",
        "name": "Suriname",
        "flag": "🇸🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SS",
        "unicode": "U+1F1F8 U+1F1F8",
        "name": "South Sudan",
        "flag": "🇸🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ST",
        "unicode": "U+1F1F8 U+1F1F9",
        "name": "São Tomé & Príncipe",
        "flag": "🇸🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SV",
        "unicode": "U+1F1F8 U+1F1FB",
        "name": "El Salvador",
        "flag": "🇸🇻",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "SX",
        "unicode": "U+1F1F8 U+1F1FD",
        "name": "Sint Maarten",
        "flag": "🇸🇽",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SY",
        "unicode": "U+1F1F8 U+1F1FE",
        "name": "Syria",
        "flag": "🇸🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "SZ",
        "unicode": "U+1F1F8 U+1F1FF",
        "name": "Swaziland",
        "flag": "🇸🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TA",
        "unicode": "U+1F1F9 U+1F1E6",
        "name": "Tristan da Cunha",
        "flag": "🇹🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TC",
        "unicode": "U+1F1F9 U+1F1E8",
        "name": "Turks & Caicos Islands",
        "flag": "🇹🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TD",
        "unicode": "U+1F1F9 U+1F1E9",
        "name": "Chad",
        "flag": "🇹🇩",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TF",
        "unicode": "U+1F1F9 U+1F1EB",
        "name": "French Southern Territories",
        "flag": "🇹🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TG",
        "unicode": "U+1F1F9 U+1F1EC",
        "name": "Togo",
        "flag": "🇹🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TH",
        "unicode": "U+1F1F9 U+1F1ED",
        "name": "Thailand",
        "flag": "🇹🇭",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TJ",
        "unicode": "U+1F1F9 U+1F1EF",
        "name": "Tajikistan",
        "flag": "🇹🇯",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TK",
        "unicode": "U+1F1F9 U+1F1F0",
        "name": "Tokelau",
        "flag": "🇹🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TL",
        "unicode": "U+1F1F9 U+1F1F1",
        "name": "Timor-Leste",
        "flag": "🇹🇱",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TM",
        "unicode": "U+1F1F9 U+1F1F2",
        "name": "Turkmenistan",
        "flag": "🇹🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TN",
        "unicode": "U+1F1F9 U+1F1F3",
        "name": "Tunisia",
        "flag": "🇹🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TO",
        "unicode": "U+1F1F9 U+1F1F4",
        "name": "Tonga",
        "flag": "🇹🇴",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TR",
        "unicode": "U+1F1F9 U+1F1F7",
        "name": "Turkey",
        "flag": "🇹🇷",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TT",
        "unicode": "U+1F1F9 U+1F1F9",
        "name": "Trinidad & Tobago",
        "flag": "🇹🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TV",
        "unicode": "U+1F1F9 U+1F1FB",
        "name": "Tuvalu",
        "flag": "🇹🇻",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TW",
        "unicode": "U+1F1F9 U+1F1FC",
        "name": "Taiwan",
        "flag": "🇹🇼",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "TZ",
        "unicode": "U+1F1F9 U+1F1FF",
        "name": "Tanzania",
        "flag": "🇹🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "UA",
        "unicode": "U+1F1FA U+1F1E6",
        "name": "Ukraine",
        "flag": "🇺🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "UG",
        "unicode": "U+1F1FA U+1F1EC",
        "name": "Uganda",
        "flag": "🇺🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "UM",
        "unicode": "U+1F1FA U+1F1F2",
        "name": "U.S. Outlying Islands",
        "flag": "🇺🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "UN",
        "unicode": "U+1F1FA U+1F1F3",
        "name": "United Nations",
        "flag": "🇺🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "US",
        "unicode": "U+1F1FA U+1F1F8",
        "name": "United States",
        "flag": "🇺🇸",
        "DATE_FORMAT": "MM/DD/YYYY",
    },
    {
        "code": "UY",
        "unicode": "U+1F1FA U+1F1FE",
        "name": "Uruguay",
        "flag": "🇺🇾",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "UZ",
        "unicode": "U+1F1FA U+1F1FF",
        "name": "Uzbekistan",
        "flag": "🇺🇿",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "VA",
        "unicode": "U+1F1FB U+1F1E6",
        "name": "Vatican City",
        "flag": "🇻🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "VC",
        "unicode": "U+1F1FB U+1F1E8",
        "name": "St. Vincent & Grenadines",
        "flag": "🇻🇨",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "VE",
        "unicode": "U+1F1FB U+1F1EA",
        "name": "Venezuela",
        "flag": "🇻🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "VG",
        "unicode": "U+1F1FB U+1F1EC",
        "name": "British Virgin Islands",
        "flag": "🇻🇬",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "VI",
        "unicode": "U+1F1FB U+1F1EE",
        "name": "U.S. Virgin Islands",
        "flag": "🇻🇮",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "VN",
        "unicode": "U+1F1FB U+1F1F3",
        "name": "Vietnam",
        "flag": "🇻🇳",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "VU",
        "unicode": "U+1F1FB U+1F1FA",
        "name": "Vanuatu",
        "flag": "🇻🇺",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "WF",
        "unicode": "U+1F1FC U+1F1EB",
        "name": "Wallis & Futuna",
        "flag": "🇼🇫",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "WS",
        "unicode": "U+1F1FC U+1F1F8",
        "name": "Samoa",
        "flag": "🇼🇸",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "XK",
        "unicode": "U+1F1FD U+1F1F0",
        "name": "Kosovo",
        "flag": "🇽🇰",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "YE",
        "unicode": "U+1F1FE U+1F1EA",
        "name": "Yemen",
        "flag": "🇾🇪",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "YT",
        "unicode": "U+1F1FE U+1F1F9",
        "name": "Mayotte",
        "flag": "🇾🇹",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ZA",
        "unicode": "U+1F1FF U+1F1E6",
        "name": "South Africa",
        "flag": "🇿🇦",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ZM",
        "unicode": "U+1F1FF U+1F1F2",
        "name": "Zambia",
        "flag": "🇿🇲",
        "DATE_FORMAT": "DD/MM/YYYY",
    },
    {
        "code": "ZW",
        "unicode": "U+1F1FF U+1F1FC",
        "name": "Zimbabwe",
        "flag": "🇿🇼",
        "DATE_FORMAT": "DD/MM/YYYY"
    }
]
function getPhonecodeAndDateformat() {
    return country;
}

module.exports = getPhonecodeAndDateformat;